POST localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QwQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2NTA0NDUwLCJ1c2VySWQiOjF9.97BH99DzxoaYnrTWnXJZGsf5F0-EyIOxfBJkcHhs3ZY

{
  "name": "Test Event",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}