DELETE http://localhost:8080/events/5
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE2NTAzNDQ2LCJ1c2VySWQiOjN9.DMpayBdgWllU2e1PPBn98Dfezjf7WAYl7UdxCcT6wmg
