PUT http://localhost:8080/events/1
content-type: application/json

{
  "name": "Updated test event",
  "description": "A test event again",
  "location": "A new location",
  "dateTime": "2025-01-02T15:30:00.000Z"
}